version: "3.9"

services:
  # -----------------------------
  # MySQL
  # -----------------------------
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: centralized_data
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - springnet
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  # -----------------------------
  # Keycloak
  # -----------------------------
  keycloak-server:
    image: quay.io/keycloak/keycloak:26.2.0
    container_name: keycloak-server
    command: [ "start-dev", "--http-relative-path=/" ]
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@123
      KC_HOSTNAME: localhost       # Important: sets frontend URL for issuer
    ports:
      - "8080:8080"
    volumes:
      - keycloak_data:/opt/keycloak/data
    networks:
      - springnet

    # -----------------------------
  # Identity Service
  # -----------------------------
  identity-service:
    build:
      context: ../identity-service
    image: devopspaxarisglobal/identity-service:latest
    container_name: identity-service

    ports:
      - "8087:8087"

    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/centralized_data?allowPublicKeyRetrieval=true&useSSL=false
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      KEYCLOAK_BASE_URL: http://keycloak-server:8080
      PROJECT_MANAGER_URL: http://project-manager:8088
      KEYCLOAK_REALM: master
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@123
      DOCKER_USERNAME: ${DOCKER_USERNAME}
      DOCKER_PASSWORD: ${DOCKER_PASSWORD}
      GITHUB_TOKEN: ${GITHUB_TOKEN}
      GITHUB_ORG: ${GITHUB_ORG}

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock   # âœ… REQUIRED

    depends_on:
      mysql-db:
        condition: service_healthy

    networks:
      - springnet


    # -----------------------------
  # Project Manager
  # -----------------------------
  project-manager:
    image: devopspaxarisglobal/product-management-service:latest
    container_name: project-manager
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/centralized_data?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      SERVER_PORT: 8088
    ports:
        - "8088:8088"
    depends_on:
      mysql-db:
        condition: service_healthy
    networks:
      - springnet
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8088/actuator/health || exit 1"]
      interval: 15s
      retries: 10
      timeout: 10s
      start_period: 120s

  # -----------------------------
  # API Gateway
  # -----------------------------
  api-gateway:
    image: devopspaxarisglobal/apigateway:latest
    container_name: api-gateway
    ports:
      - "8085:8085"
    environment:
      PROJECT_MANAGEMENT_BASE_URL: http://project-manager:8088
      IDENTITY_SERVICE_URL: http://identity-service:8087
      KEYCLOAK_BASE_URL: http://keycloak-server:8080
    depends_on:
      mysql-db:
        condition: service_healthy
      project-manager:
        condition: service_healthy
    networks:
      - springnet
    restart: unless-stopped


# -----------------------------
# Network & Volumes
# -----------------------------
networks:
  springnet:
    driver: bridge

volumes:
  mysql_data:
  keycloak_data:


