name: Central Docker Image Builder

on:
  repository_dispatch:
    types: [build-image]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggered repository
        uses: actions/checkout@v4
        with:
          repository: ${{ github.event.client_payload.repo }}
          ref: main
          token: ${{ secrets.GH_ACCESS_TOKEN }}

      - name: Set up JDK 21 with Maven cache
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '21'
          cache: maven

      - name: Build using Maven
        run: mvn -B clean package -DskipTests

      - name: Docker Hub Login
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build & Push Image (Jib)
        run: mvn -B jib:build -DskipTests
